/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	etcd "github.com/xmudrii/etcdstorage-apiserver/pkg/apis/etcd"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEtcdStorages implements EtcdStorageInterface
type FakeEtcdStorages struct {
	Fake *FakeEtcd
	ns   string
}

var etcdstoragesResource = schema.GroupVersionResource{Group: "etcd.k8s.io", Version: "", Resource: "etcdstorages"}

var etcdstoragesKind = schema.GroupVersionKind{Group: "etcd.k8s.io", Version: "", Kind: "EtcdStorage"}

// Get takes name of the etcdStorage, and returns the corresponding etcdStorage object, and an error if there is any.
func (c *FakeEtcdStorages) Get(name string, options v1.GetOptions) (result *etcd.EtcdStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(etcdstoragesResource, c.ns, name), &etcd.EtcdStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*etcd.EtcdStorage), err
}

// List takes label and field selectors, and returns the list of EtcdStorages that match those selectors.
func (c *FakeEtcdStorages) List(opts v1.ListOptions) (result *etcd.EtcdStorageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(etcdstoragesResource, etcdstoragesKind, c.ns, opts), &etcd.EtcdStorageList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &etcd.EtcdStorageList{}
	for _, item := range obj.(*etcd.EtcdStorageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested etcdStorages.
func (c *FakeEtcdStorages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(etcdstoragesResource, c.ns, opts))

}

// Create takes the representation of a etcdStorage and creates it.  Returns the server's representation of the etcdStorage, and an error, if there is any.
func (c *FakeEtcdStorages) Create(etcdStorage *etcd.EtcdStorage) (result *etcd.EtcdStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(etcdstoragesResource, c.ns, etcdStorage), &etcd.EtcdStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*etcd.EtcdStorage), err
}

// Update takes the representation of a etcdStorage and updates it. Returns the server's representation of the etcdStorage, and an error, if there is any.
func (c *FakeEtcdStorages) Update(etcdStorage *etcd.EtcdStorage) (result *etcd.EtcdStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(etcdstoragesResource, c.ns, etcdStorage), &etcd.EtcdStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*etcd.EtcdStorage), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEtcdStorages) UpdateStatus(etcdStorage *etcd.EtcdStorage) (*etcd.EtcdStorage, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(etcdstoragesResource, "status", c.ns, etcdStorage), &etcd.EtcdStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*etcd.EtcdStorage), err
}

// Delete takes name of the etcdStorage and deletes it. Returns an error if one occurs.
func (c *FakeEtcdStorages) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(etcdstoragesResource, c.ns, name), &etcd.EtcdStorage{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEtcdStorages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(etcdstoragesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &etcd.EtcdStorageList{})
	return err
}

// Patch applies the patch and returns the patched etcdStorage.
func (c *FakeEtcdStorages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *etcd.EtcdStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(etcdstoragesResource, c.ns, name, data, subresources...), &etcd.EtcdStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*etcd.EtcdStorage), err
}
